### ISSUE TITLE
Is there a plan to replace the deprecated API?

### ISSUE THREAD

**Issue by 2000calories** [BytesZero/app_installer#10]
Thanks for developing this package.
When I built the app bundle, there was a altert`AppInstallerPlugin.java uses or overrides a deprecated API.`
Is there a plan to replace the deprecated API?

**Comment by yy1300326388** [comment]
Can you output more log information? I will update in time

**Comment by 2000calories** [comment]
Here is the warning message. I am not a java developer. have no idea about the deprecated API.
```
Note: /Users/.../development/flutter/.pub-cache/hosted/pub.dartlang.org/app_installer-1.1.0/android/src/main/java/com/zero/app_installer/AppInstallerPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
```

**Comment by yy1300326388** [comment]
Can you provide me with your configuration file, the important thing is compileSdkVersion

**Comment by 2000calories** [comment]
```
android {
    compileSdkVersion 31

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 31
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }
}
```

**Comment by Tindtily** [comment]
.pub-cache/hosted/pub.dev/app_installer-1.3.0/android/src/main/java/com/zero/app_installer/AppInstallerPlugin.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。

同样的问题吧

**Comment by BytesZero** [comment]
@Tindtily  Yes, it does not affect specific functions for the time being. So please ignore it first and it will be further processed later.

Thank you for your feedback again.

If you have specific suggestions or ideas, please submit a pull request.

**Comment by BytesZero** [comment]
@Tindtily @2000calories @HannesGitH 
I have found the specific code location. Originally, during the process from flutter plugin v1 to v2, this code was forgotten to be deleted. It will be deleted in the next version.

![image](https://github.com/user-attachments/assets/9a1618f5-bda3-4ed9-ac77-c812658f749d)
