### ISSUE TITLE
xcode无法找到module

### ISSUE THREAD

**Issue by BraveAction** [BytesZero/app_installer#13]
app/ios/Runner/GeneratedPluginRegistrant.m
app/ios/Runner/GeneratedPluginRegistrant.m:12:9 Module 'app_installer' not found

**Comment by BytesZero** [comment]
发一下Flutter版本等信息

**Comment by BraveAction** [comment]
Flutter 2.5.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ffb2ecea52 (2 years, 4 months ago) • 2021-09-17 15:26:33 -0400
Engine • revision b3af521a05
Tools • Dart 2.14.2

pod --version  1.13.0

app_installer: 1.0.0

xcode  14.2

**Comment by BraveAction** [comment]
抱歉,自己这边的问题(从androidStudio打开xcode项目选错了目录)

**Comment by BytesZero** [comment]
好的，解决了就好，记得点个 Star
