### ISSUE TITLE
Android resource linking failed

### ISSUE THREAD

**Issue by HudsonAfonso** [BytesZero/app_installer#14]
ERROR: project_folder/build/app_installer/intermediates/merged_res/release/values/values.xml:211: AAPT: error: resource android:attr/lStar not found.

    • Flutter version 3.24.0 on channel stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (7 days ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

**Comment by BytesZero** [comment]
@HudsonAfonso If you encounter this problem after upgrading to the latest version of Flutter, you can refer to this for modification. The plugin does not need to be modified.

https://stackoverflow.com/questions/69033022/message-error-resource-androidattr-lstar-not-found

```
compileSdkVersion 31
```

**Comment by HudsonAfonso** [comment]
using `compileSdkVersion 34` same error...

**Comment by BytesZero** [comment]
@HudsonAfonso  I have fixed this issue and will release a new version `v1.2.0` later

**Comment by BytesZero** [comment]
https://pub.dev/packages/app_installer

**Comment by BytesZero** [comment]
@imranbajwa2024
