### ISSUE TITLE
android.permission.REQUEST_INSTALL_PACKAGES 这个谷歌上架已经禁止了

### ISSUE THREAD

**Issue by bxiao0719** [BytesZero/app_installer#16]
android.permission.REQUEST_INSTALL_PACKAGES 这个谷歌上架已经禁止了 请修复

**Comment by BytesZero** [comment]
后续将删除此能力

**Comment by BytesZero** [comment]
You can consider using the following code to remove it, but at this time you will not be able to use the `AppInstaller.installApk` method.

- `AndroidManifest.xml`

``` xml
<!-- Use tools:node="remove" to remove permissions. -->
<uses-permission-sdk-23 android:name="android.permission.REQUEST_INSTALL_PACKAGES" tools:node="remove"/>
```

**Comment by bxiao0719** [comment]
感谢

**Comment by zhecaoapp** [comment]
为什么加了这个权限以后直接报错，无法启动了
